In [1]:
import numpy as np
#Talbica 10 zer
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
#Tablica 10 piątek
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#Tablica zawierająca liczby od 10 do 50
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
#Macierz o wymiarach 3x3 zawierającą liczby od 0 do 8
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
#Macierz jednostkowa o wymiarach 3x3,
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
#Macierz o wymiarach 5x5 zawierającą liczby 
# z dystrybucji normalnej (Gaussa)
np.random.randn(5, 5)

array([[-0.21989544, -0.26683331, -0.60770147, -1.27841824,  1.24627933],
       [ 0.90854596, -0.27742614,  0.20417676, -1.01549009, -1.27767167],
       [ 0.17807166,  0.01710769,  0.88661075, -0.32820695,  0.70998201],
       [-0.11535377,  0.0368479 ,  1.12114294, -0.62206011,  0.26238856],
       [-1.43410643, -1.56464298,  0.63721169,  0.38196042, -0.49000722]])

In [24]:
#Macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01
np.arange(1,101,1).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [31]:
#Tablicę zawierającą 20 liniowo rozłożonych liczb 
# między 0 a 1 (włącznie z 0 i 1)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [69]:
#Tablica zawierająca losowe liczby z przedziału (1, 25), 
# następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami
arr = np.random.randint(25, size=(5,5))+1
print(arr)

[[16 24  8 10 19]
 [16 19  7 24 15]
 [13  5 16 14  4]
 [ 9  1 16 14  1]
 [ 4 16 15 14  8]]


In [70]:
#suma wszystkich liczb w ww. macierzy
arr.sum()

308

In [71]:
#średnia wszystkich liczb w ww. macierzy
arr.mean()

12.32

In [72]:
#standardowa dewiacja dla liczb w ww. macierzy
arr.std()

6.271969387680396

In [73]:
#oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy
print()
b = arr.sum(0)
print(b)


[58 65 62 76 47]


In [75]:
#Utwórz macierz o wymiarach 5x5 
# zawierającą losowe liczby z przedziału (0, 100) i:
arr2 = np.random.randint(100, size=(5,5))
print(arr2)

[[91  3 97 56 64]
 [70 93 48 41 61]
 [15 89  1 65 88]
 [69 77 81 14  8]
 [18 16 69 51  8]]


In [78]:
#oblicz medianę tych liczb
np.median(arr2)

61.0

In [79]:
#najmniejszą liczbę tej macierzy
np.min(arr2)

1

In [80]:
#największą liczbę tej macierzy
np.max(arr2)

97

In [81]:
#Utwórz macierz o wymiarach różnych od siebie i większych od 1, 
# zawierającą losowe liczby z przedziału (0, 100) 
#  i dokonaj jej transpozycji
arr3 = np.random.randint(100, size=(4,6))
print(arr3)
arr4 = np.transpose(arr3)
print(arr4)

[[45 49 13 64 54 66]
 [73 63 53 56  9 52]
 [45 21  1 84 80 43]
 [43 66 76 69 29 31]]
[[45 73 45 43]
 [49 63 21 66]
 [13 53  1 76]
 [64 56 84 69]
 [54  9 80 29]
 [66 52 43 31]]


In [90]:
#Utwórz dwie macierze o odpowiednich wymiarach (doczytać), 
# większych od 2 i dodaj je do siebie

mtx1 = np.random.randint(25, size=(3,4))+1
print(mtx1)
print("-----------------------")
mtx2 = np.random.randint(25, size=(3,4))+1
print(mtx2)
print("-----------------------")
mtx3 = mtx1 + mtx2
print(mtx3)
print("-----------------------")

[[18 16 15 18]
 [15 15 16  7]
 [21 20  5 15]]
-----------------------
[[ 9 21  9 24]
 [ 7  3  8  2]
 [18 11 12 24]]
-----------------------
[[27 37 24 42]
 [22 18 24  9]
 [39 31 17 39]]
-----------------------
[[162 336 135 432]
 [105  45 128  14]
 [378 220  60 360]]
-----------------------


In [108]:
#Utwórz dwie macierze o odpowiednich wymiarach (doczytać) różńych od siebie, 
# większych od 2 i pomnóż je przez siebie

x1 = np.random.randint(10, size=(2,5))
print(x1)
print("-----------------------")
x2 = np.random.randint(10, size=(5,2))
print(x2)
print("-----------------------")
np.matmul(x1, x2)

[[4 6 2 8 1]
 [5 6 8 3 4]]
-----------------------
[[3 3]
 [3 6]
 [8 1]
 [8 6]
 [9 6]]
-----------------------


array([[119, 104],
       [157, 101]])